export const GET_PRODUCTS = "GET_PRODUCTS"
export const GET_PRODUCTSBYNAME = "GET_PRODUCTSBYNAME"
export const POST_PRODUCT = "POST_PRODUCT"
export const GET_SIZES = "GET_SIZES"
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT = 'LOGOUT';